### ISSUE TITLE
Nano-S HW wallet issue

### ISSUE THREAD

**Issue by bitcoin333** [randlabs/myalgo-connect#33] opened 2021-05-28 16:10 UTC
When using a Nano-S hardware wallet for signing, MyAlgo connect works correctly only the first time: asks for password in the popup window, then displays the txn details on the Nano-S and waits for Accept/Reject.  But during the next call, it asks for the password, then the popup disappears, and the Nano-S is not asked for signing. Test was done on Testnet, using Firefox and Chrome browsers.

**Comment by Alex99y** [comment] 2021-05-28 17:33
Hello @bitcoin333 ! Are you using Windows 10 OS? What is your Algorand ledger app version?

**Comment by bitcoin333** [comment] 2021-05-29 08:02
Win 7. Nano S Algorand app version 1.2.11

**Comment by Alex99y** [comment] 2021-05-29 12:22
@bitcoin333 yes, it's a minor bug from ledger live, but don't worry about that, you have the last version. Can you try the operation again, and tell me which transport is using MyAlgo Connect?. You can find it opening the popup inspector and pressing the console tab.

**Comment by bitcoin333** [comment] 2021-05-29 14:01
Firefox:  Using TransportU2F
Chrome: Using TransportWebHID

**Comment by Alex99y** [comment] 2021-05-31 15:08
@bitcoin333 Both browsers are failing? Can you provide me MyAlgoConnect.signTransaction error output?.

**Comment by Yodag7354** [comment] 2021-05-31 17:10
What who are you and what do you want

**Comment by bitcoin333** [comment] 2021-06-02 08:52
Yes, both are "failing". The popup simply disappears, and I get back a signed transaction, without displaying the tx parameters on the Nano-S and waiting to accept/reject the transacion. Then this signed transaction is combined with two other txns, one of them a "pay" txn signed by the algosdk, the other is an "axfer" txn, signed by "lsig", and the 3 txns are sent as a raw transaction through algod. (PureStake). And then I get "Bad request".

**Comment by Alex99y** [comment] 2021-06-02 12:47
@bitcoin333 Okay. It is possible to share with me the output of MyAlgo Connect `signTransaction()` method in base64?

```js
const signedTx = await myAlgoWallet.signTransaction(tx);
const signedTxB64= Buffer.from(signedTx).toString("base64"); // I need this
```
If it is private, you can send me it on Discord in PM

**Comment by bitcoin333** [comment] 2021-06-03 08:03
```
	let signedTxn2ma = await myalgoConnect.signTransaction(txn2ma);
	let signedTxn2ma_b64 = sodium.to_base64(signedTxn2ma.blob);
	let signedTxn2ma_hex = sodium.to_hex(signedTxn2ma.blob);
	console.log('signedTxn2ma_b64:', signedTxn2ma_b64);
	console.log('signedTxn2ma_hex:', signedTxn2ma_hex);
```

```
signedTxn2ma_b64: gqNzaWfEUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdW5rbm93biBmaWVsZCBncnCjdHhuiqNhbXTOAAb1QKNmZWXNA-iiZnbOAN3ywKNnZW6sdGVzdG5ldC12MS4womdoxCBIY7UYpLPITsgQ8i1PEIHLD3HwWaesIN7GL39w5Qk6IqNncnDEIOH453Qfbqe-_2LvnFBxA75A64-PRfsLSDWKEHjPXEfMomx2zgDd9qijcmN2xCCCuSiwxVscgCzLnAbzRoI_jglmS0g-mtz6hrmkwhBTkqNzbmTEIFXV2a6Om-6N-wm7DDOZzT6FcB3xp3L4RKUGKqCArbGcpHR5cGWjcGF5 web_market.js:153:10
signedTxn2ma_hex: 82a3736967c4520000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000756e6b6e6f776e206669656c6420677270a374786e8aa3616d74ce0006f540a3666565cd03e8a26676ce00ddf2c0a367656eac746573746e65742d76312e30a26768c4204863b518a4b3c84ec810f22d4f1081cb0f71f059a7ac20dec62f7f70e5093a22a3677270c420e1f8e7741f6ea7beff62ef9c507103be40eb8f8f45fb0b48358a1078cf5c47cca26c76ce00ddf6a8a3726376c42082b928b0c55b1c802ccb9c06f346823f8e09664b483e9adcfa86b9a4c2105392a3736e64c42055d5d9ae8e9bee8dfb09bb0c3399cd3e85701df1a772f844a5062aa080adb19ca474797065a3706179
```

**Comment by Alex99y** [comment] 2021-06-03 19:23
@bitcoin333 Thanks for reporting this issue. The problem is not related to MyAlgo Connect. Currently, the Algorand ledger app does not support group transactions (grp field), we didn't know that. We hope that the Algorand team adds support for group id soon.

Sorry for any inconvenience. 

https://github.com/algorand/ledger-app-algorand/issues/38

**Comment by Alex99y** [comment] 2021-06-28 12:27
Update:
Algorand's Team fixed this issue a few days ago. Now we need to wait until Ledger Live pull those commits and upload the new version.
https://github.com/LedgerHQ/app-algorand

**Comment by Alex99y** [comment] 2021-08-13 23:19
Closing, now Ledger Live provides the latest version of Algorand App that provides support for signing transactions that include the group field

**Closed by Alex99y** 2021-08-13 23:19 UTC
